server:
  port: 9090

#db configuration
#create,update,create-drop,validate
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_app_apis
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
   hibernate:
       ddl-auto: update
   show-sql: true

